"""empty message

Revision ID: e713fe441d81
Revises: 1ebc7e296472
Create Date: 2026-01-24 19:46:50.707345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e713fe441d81'
down_revision: Union[str, Sequence[str], None] = '1ebc7e296472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя в Telegram (первичный ключ)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_column('admins', 'user_id')
    op.alter_column('converted_videos', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('converted_videos', 'format',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_index(op.f('ix_converted_videos_id'), table_name='converted_videos')
    op.drop_index(op.f('ix_promo_links_id'), table_name='promo_links')
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.add_column('users', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(op.f('users_invited_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])
    op.drop_column('users', 'invited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_invited_by_fkey'), 'users', 'users', ['invited_by'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('users', 'referrer_id')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.create_index(op.f('ix_promo_links_id'), 'promo_links', ['id'], unique=False)
    op.create_index(op.f('ix_converted_videos_id'), 'converted_videos', ['id'], unique=False)
    op.alter_column('converted_videos', 'format',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('converted_videos', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('admins', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.alter_column('admins', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя в Telegram (первичный ключ)',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
