"""empty message

Revision ID: f8080fe34a10
Revises: e713fe441d81
Create Date: 2026-01-25 13:01:38.243206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8080fe34a10'
down_revision: Union[str, Sequence[str], None] = 'e713fe441d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=False)
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_constraint(op.f('users_referral_code_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_unique_constraint(op.f('users_referral_code_key'), 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
